### PR TITLE
added my solution

### PR DESCRIPTION
**Pull request by karan0046**
looking forward for next task ,and please let me know if error still exists

### CODE REVIEW

**Comment by phantom654** [comment]
@karan0046 
You did a great job and most of the errors are resolved.
1. Please give a proper technical reason to change char* to string. [Tip : do some research on basics of pointers and string functions(strlen() in this case)]
2. There's a very small error based on modular mathematics. [Tip  : read how modulo can be distributed in mathematical operators.]

**Comment by phantom654** [comment]
@karan0046 
Your current solution is giving WA for this input : "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
image
expected answer : 199

**Comment by karan0046** [comment]
@phantom654 
I totally forgot that modulo doesn't work like normal algebra ,thankyou for bringing in notice, I had updated the changes.

**Comment by phantom654** [comment]
@karan0046 
Your current solution is perfect. But,
1. The reason is still not correct to change char* to string. See if it was char str[100009]. Here also str stores the base address as in the case of char* . And you might know that char str[100009] will give no error. 
As I stated before carefully read basics of pointer and Time complexity of inbuilt string functions (strlen() and str.length() in this case)

**Comment by phantom654** [comment]
@karan0046 Think something related to dangling pointer and uninitialised pointers.

**Pull request merged**
