### PR TITLE
Codelines

### PR DESCRIPTION
**Pull request by Kalpana200**
I have edited the code

### CODE REVIEW

**Comment by phantom654** [comment]
@Kalpana200 It seems you have not read the Problem statement completely. There are many restrictions on the changes you can make. I am mentioning them once more. 
2. If you are changing any of the constants defined(like mod or p), the absolute change should be <=100
 	i.e. |new_value - old_value| <= 100

You have violated this by making mod 1e9+7 from 2^64
Also you didn't put any comments for the changes you made.

**Comment by Kalpana200** [comment]
Sir , I have updated by code keeping in mind all constraints and added comments to explain what I have edited in code and why.

**Comment by Kalpana200** [comment]
PLEASE ,let me know if I'm still wrong anywhere.

**Comment by phantom654** [comment]
@Kalpana200 Maximum value that can be stored in a long long int is 2^63 - 1
And please Tag me from next time while commenting for faster response.

**Comment by Kalpana200** [comment]
So  how is it possible to get a prime number with just creating difference max. upto 100 in 2^64 
@phantom654

**Comment by phantom654** [comment]
@Kalpana200 that's the issue you have to solve. I suggest reading more on data types in c++.
Also [Line 4] is not the only line that will cause overflow. In [Line 45] we are multiplying (hash_prefix[str.length()-1] - hash_prefix[i-2]) (which is <=2^64) and binpow(binpow(p,i-1,mod),mod- 2,mod) (which is <=2^64). So the multiplication will be of order 2^128 and that's even more worse.
Please look more closely and verify each and every line. You are just few steps from solving the issue :)

**Comment by phantom654** [comment]
@Kalpana200 Also there are some changes for which you have not provided a valid reason. Like Line 38 [ Changing char *str to string. Changing strlen(str) to str.length(). 
This repository has merely 60-70 lines of code so we need to focus on such small details too or nothing much will be left to do.

**Comment by Kalpana200** [comment]
PLEASE, check my newly updated file @phantom654

**Comment by phantom654** [comment]
@Kalpana200 
1. Your logic behind changing char* to string is wrong. I think you refered to this article [https://www.geeksforgeeks.org/char-vs-stdstring-vs-char-c/]. But read carefully it says it's for that example only. There are ways by which we can make char* to point to a user defined location and then take input in it. But I will allow changing char* to string if you provide a valid reason for that.
2. In [Line 45] of your updated code,  one can't directly divide as we have applied modulo on numerator. Read more on modular arithmetic's.
Tip : There are many more data types in c++ other than int,long,double,float etc.

**Comment by Kalpana200** [comment]
@phantom654  using char*,  giving me a runtime error

**Comment by Kalpana200** [comment]
@phantom654  
In this line ,
		hash_suffix[str.length()-i] =((hash_prefix[str.length()-1] - hash_prefix[i-2]) * binpow(binpow(p,i-1,mod),mod- 
       2,mod))%mod;    
value after modulo can be stored in unsigned long long int.

**Comment by phantom654** [comment]
> @phantom654 using char*, giving me a runtime error

Yes give reason for that.

**Comment by phantom654** [comment]
> @phantom654
> In this line ,
> hash_suffix[str.length()-i] =((hash_prefix[str.length()-1] - hash_prefix[i-2]) * binpow(binpow(p,i-1,mod),mod-
> 2,mod))%mod;
> value after modulo can be stored in unsigned long long int.

I can't identify all the errors for you. If your solution does not pass all the test cases its wrong.

**Comment by phantom654** [comment]
@Kalpana200 
image

Your current solution gives output 8, which is clearly wrong.

**Comment by phantom654** [comment]
@Kalpana200 As I also stated before. Read about data types in c++. There are many more than one commonly uses.

**Pull request closed without merging**
