### PR TITLE
Create IIT2019043.cpp

### PR DESCRIPTION
**Pull request by Tushargupta9800**
I've added in comments what changes I've done
IIT2019043

### CODE REVIEW

**Comment by phantom654** [comment]
@Tushargupta9800 
1. Code is giving segmentation fault for every input. Please verify the solution with few test cases before making a Pull Request. 
2. There are few more constraints on p other than it being greater than number of English alphabets to ensure a collision free hash(approximately collision free). I suggest you to read a bit more on String Hashing. Your value for p will also work in most of the cases, but to ensure minimum collisions try to improve 'p' a bit more.
3. Please give the logic behind changing (str[i]-'a') to (str[i]-'a'+1).
4. In Line 53, one can't directly divide as we have applied modulo on numerator. Read more on modular arithmetic's. 
5. As mod is very large (about maximum value that can be stored in unsigned long long int), if we multiply two values it will give overflow. In this case also please read more on modular arithmetic's.
6. Recheck the complexity of the code.

**Comment by Tushargupta9800** [comment]
1) I've tried some of my own test case but It never gives me segmentation fault but I'll surely look for other possible cases.
2) OK I'll look what p should be.
3) When I take the input like:- aaaaa (multiple a's) then It gives me (wrong ans 16) as because 'a' - 'a' = 0 so, rather starting from 0 I started from 1.
4) I almost forgot, I'll fix that.
5) Ok I'll read it
6) The complexity is same as the solution provided I didn't add any Extra loops!!!

**Comment by phantom654** [comment]
1 I checked it on a local compiler (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) , and an online compiler(https://www.onlinegdb.com/) and both gave me segmentation fault. Can you please specify which compiler you are using?
2 Yes you are correct. You should have mentioned that in comments in your code.
6 The complexity of solution provided to you is O((length ^ 2) * log(mod)) but expected complexity is O(length * log(mod))

**Comment by Tushargupta9800** [comment]
1) I'd use gfg ide with simple inputs like aaaaaaa, bbbbbbb, abcab and other such strings ( https://ide.geeksforgeeks.org/vX0uvq9ybI )
2) Ok I'll update it
6) I didn't get How O((length ^ 2) * log(mod)) 
look:-
computeHash function is of O(length)

then:-
```
for(long long int i=strlen(str);i>1;i--)
	{
	hash_suffix[strlen(str)-i] = ((hash_prefix[strlen(str) - 1] - hash_prefix[i-2])/binpow(p,i-1,mod))%mod;
	}
```
it is O((length) * log(mod))
```
for(int i=0;i<strlen(str)-1;i++)
	{
		m_prefix[hash_prefix[i]]++;
		m_suffix[hash_suffix[i]]++; 
	}
```
it is O(length)

```
for(auto it:m_prefix)
	{
		long long int f1=it.second;
		long long int f2=m_suffix[it.first];

		ans += f1 * f2;
	}
````
this one too O(length)
So, how come the complexity be O((length ^ 2) * log(mod)) 

PLEASE, let me know if I'm wrong anywhere....

**Comment by phantom654** [comment]
1. Its giving error for large inputs. You may check for input "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
3. This is a CC repository and one can't explain everything otherwise nothing will be left to do.

**Comment by phantom654** [comment]
I can give some hints for time complexity.
You might be knowing that 10^8 operation take approximately 1 sec. So if complexity of the code was O(length * log(mod)) it would have been executed in about 0.06 sec for length = 100000.

image

But you may see here its taking about 1.4sec. (much more than than 0.06)

**Pull request closed without merging**
